package com.mcnmr.countryflagkit

import java.util.*

class Flags {
    companion object{
        const val UNKNOWN_COUNTRY_CODE = -1

        fun get(countryCode: String): Int{
            return when(countryCode.toUpperCase(Locale.getDefault())){
                CountryCode.Afghanistan -> R.drawable.ic_flag_af
                CountryCode.Albania -> R.drawable.ic_flag_al
                CountryCode.Algeria -> R.drawable.ic_flag_dz
                CountryCode.AmericanSamoa -> R.drawable.ic_flag_as
                CountryCode.Andorra -> R.drawable.ic_flag_ad
                CountryCode.Angola -> R.drawable.ic_flag_ao
                CountryCode.Anguilla -> R.drawable.ic_flag_ai
                CountryCode.AntiguaAndBarbuda -> R.drawable.ic_flag_ag
                CountryCode.Argentina -> R.drawable.ic_flag_ar
                CountryCode.Armenia -> R.drawable.ic_flag_am
                CountryCode.Aruba -> R.drawable.ic_flag_aw
                CountryCode.Australia -> R.drawable.ic_flag_au
                CountryCode.Austria -> R.drawable.ic_flag_at
                CountryCode.Azerbaijan -> R.drawable.ic_flag_az
                CountryCode.Bahamas -> R.drawable.ic_flag_bs
                CountryCode.Bahrain -> R.drawable.ic_flag_bh
                CountryCode.Bangladesh -> R.drawable.ic_flag_bd
                CountryCode.Barbados -> R.drawable.ic_flag_bb
                CountryCode.Belarus -> R.drawable.ic_flag_be
                CountryCode.Belgium -> R.drawable.ic_flag_by
                CountryCode.Belize -> R.drawable.ic_flag_bz
                CountryCode.Benin -> R.drawable.ic_flag_bj
                CountryCode.Bermuda -> R.drawable.ic_flag_bt
                CountryCode.Bhutan -> R.drawable.ic_flag_bm
                CountryCode.Bolivia -> R.drawable.ic_flag_bo
                CountryCode.BosniaAndHerzegovina -> R.drawable.ic_flag_ba
                CountryCode.Botswana -> R.drawable.ic_flag_bw
                CountryCode.Brazil -> R.drawable.ic_flag_br
                CountryCode.BritishIndianOceanTerritory -> R.drawable.ic_flag_io
                CountryCode.BritishVirginIsland -> R.drawable.ic_flag_vg
                CountryCode.Brunei -> R.drawable.ic_flag_bn
                CountryCode.Bulgaria -> R.drawable.ic_flag_bg
                CountryCode.BurkinaFaso -> R.drawable.ic_flag_bf
                CountryCode.Burundi -> R.drawable.ic_flag_bi
                CountryCode.Cambodia -> R.drawable.ic_flag_kh
                CountryCode.Cameroon -> R.drawable.ic_flag_cm
                CountryCode.Canada -> R.drawable.ic_flag_ca
                CountryCode.CapeVerde -> R.drawable.ic_flag_cv
                CountryCode.CaymanIslands -> R.drawable.ic_flag_ky
                CountryCode.CentralAfricanRepublic -> R.drawable.ic_flag_cf
                CountryCode.Chad -> R.drawable.ic_flag_td
                CountryCode.Chile -> R.drawable.ic_flag_cl
                CountryCode.China -> R.drawable.ic_flag_cn
                CountryCode.ChristmastIsland -> R.drawable.ic_flag_cx
                CountryCode.CocosIslands -> R.drawable.ic_flag_cc
                CountryCode.Colombia -> R.drawable.ic_flag_co
                CountryCode.Comoros -> R.drawable.ic_flag_km
                CountryCode.CookIslands -> R.drawable.ic_flag_ck
                CountryCode.CostaRica -> R.drawable.ic_flag_cr
                CountryCode.Croatia -> R.drawable.ic_flag_hr
                CountryCode.Cuba -> R.drawable.ic_flag_cu
                CountryCode.Curacao -> R.drawable.ic_flag_cw
                CountryCode.Cyprus -> R.drawable.ic_flag_cy
                CountryCode.CzechRepublic -> R.drawable.ic_flag_cz
                CountryCode.DemocraticRepublicCongo -> R.drawable.ic_flag_cd
                CountryCode.Denmark -> R.drawable.ic_flag_dk
                CountryCode.Djibouti -> R.drawable.ic_flag_dj
                CountryCode.Dominica -> R.drawable.ic_flag_dm
                CountryCode.DominicanRepublic -> R.drawable.ic_flag_do
                CountryCode.EastTimor -> R.drawable.ic_flag_tl
                CountryCode.Ecuador -> R.drawable.ic_flag_ec
                CountryCode.Egypt -> R.drawable.ic_flag_eg
                CountryCode.ElSalvador -> R.drawable.ic_flag_sv
                CountryCode.EquatorialGuinea -> R.drawable.ic_flag_gq
                CountryCode.Eritrea -> R.drawable.ic_flag_er
                CountryCode.Estonia -> R.drawable.ic_flag_ee
                CountryCode.Ethiopia -> R.drawable.ic_flag_et
                CountryCode.FalklandIslands -> R.drawable.ic_flag_fk
                CountryCode.FaroeIslands -> R.drawable.ic_flag_fo
                CountryCode.Fiji -> R.drawable.ic_flag_fj
                CountryCode.Finland -> R.drawable.ic_flag_fi
                CountryCode.France -> R.drawable.ic_flag_fr
                CountryCode.FranchPolynesia -> R.drawable.ic_flag_pf
                CountryCode.Gabon -> R.drawable.ic_flag_ga
                CountryCode.Gambia -> R.drawable.ic_flag_gm
                CountryCode.Georgia -> R.drawable.ic_flag_ge
                CountryCode.Germany -> R.drawable.ic_flag_de
                CountryCode.Ghana -> R.drawable.ic_flag_gh
                CountryCode.Gibraltar -> R.drawable.ic_flag_gi
                CountryCode.Greece -> R.drawable.ic_flag_gr
                CountryCode.Greenland -> R.drawable.ic_flag_gl
                CountryCode.Grenada -> R.drawable.ic_flag_gd
                CountryCode.Guam -> R.drawable.ic_flag_gu
                CountryCode.Guatemala -> R.drawable.ic_flag_gt
                CountryCode.Guernsey -> R.drawable.ic_flag_gg
                CountryCode.Guinea -> R.drawable.ic_flag_gn
                CountryCode.GuineaBissaw -> R.drawable.ic_flag_gw
                CountryCode.Guyana -> R.drawable.ic_flag_gy
                CountryCode.Haiti -> R.drawable.ic_flag_ht
                CountryCode.Honduras -> R.drawable.ic_flag_hn
                CountryCode.Hongkong -> R.drawable.ic_flag_hk
                CountryCode.Hungary -> R.drawable.ic_flag_hu
                CountryCode.Iceland -> R.drawable.ic_flag_is
                CountryCode.India -> R.drawable.ic_flag_in
                CountryCode.Indonesia -> R.drawable.ic_flag_id
                CountryCode.Iran -> R.drawable.ic_flag_ir
                CountryCode.Iraq -> R.drawable.ic_flag_iq
                CountryCode.Ireland -> R.drawable.ic_flag_ie
                CountryCode.IsleOfMan -> R.drawable.ic_flag_im
                CountryCode.Israel -> R.drawable.ic_flag_il
                CountryCode.Italy -> R.drawable.ic_flag_it
                CountryCode.IvoryCoast -> R.drawable.ic_flag_ci
                CountryCode.Jamaica -> R.drawable.ic_flag_jm
                CountryCode.Japan -> R.drawable.ic_flag_jp
                CountryCode.Jersey -> R.drawable.ic_flag_je
                CountryCode.Jordan -> R.drawable.ic_flag_jo
                CountryCode.Kazakhstan -> R.drawable.ic_flag_kz
                CountryCode.Kenya -> R.drawable.ic_flag_ke
                CountryCode.Kiribati -> R.drawable.ic_flag_ki
                CountryCode.Kosovo -> R.drawable.ic_flag_xk
                CountryCode.Kuwait -> R.drawable.ic_flag_kw
                CountryCode.Kyrgyzstan -> R.drawable.ic_flag_kg
                CountryCode.Laos -> R.drawable.ic_flag_la
                CountryCode.Latvia -> R.drawable.ic_flag_lv
                CountryCode.Lebanon -> R.drawable.ic_flag_lb
                CountryCode.Lesotho -> R.drawable.ic_flag_ls
                CountryCode.Liberia -> R.drawable.ic_flag_lr
                CountryCode.Libya -> R.drawable.ic_flag_ly
                CountryCode.Liechtenstein -> R.drawable.ic_flag_li
                CountryCode.Lithuania -> R.drawable.ic_flag_lt
                CountryCode.Luxembourg -> R.drawable.ic_flag_lu
                CountryCode.Macau -> R.drawable.ic_flag_mo
                CountryCode.Macedonia -> R.drawable.ic_flag_mk
                CountryCode.Madagascar -> R.drawable.ic_flag_mg
                CountryCode.Malawi -> R.drawable.ic_flag_mw
                CountryCode.Malaysia -> R.drawable.ic_flag_my
                CountryCode.Maldives -> R.drawable.ic_flag_mv
                CountryCode.Mali -> R.drawable.ic_flag_ml
                CountryCode.Malta -> R.drawable.ic_flag_mt
                CountryCode.MarshallIslands -> R.drawable.ic_flag_mh
                CountryCode.Mauritania -> R.drawable.ic_flag_mr
                CountryCode.Mauritius -> R.drawable.ic_flag_mu
                CountryCode.Mayotte -> R.drawable.ic_flag_yt
                CountryCode.Mexico -> R.drawable.ic_flag_mx
                CountryCode.Micronesia -> R.drawable.ic_flag_fm
                CountryCode.Moldova -> R.drawable.ic_flag_md
                CountryCode.Monaco -> R.drawable.ic_flag_mc
                CountryCode.Mongolia -> R.drawable.ic_flag_mn
                CountryCode.Montenegro -> R.drawable.ic_flag_me
                CountryCode.Montserrat -> R.drawable.ic_flag_ms
                CountryCode.Morocco -> R.drawable.ic_flag_ma
                CountryCode.Mozambique -> R.drawable.ic_flag_mz
                CountryCode.Myanmar -> R.drawable.ic_flag_mm
                CountryCode.Namibia -> R.drawable.ic_flag_na
                CountryCode.Nauru -> R.drawable.ic_flag_nr
                CountryCode.Nepal -> R.drawable.ic_flag_np
                CountryCode.Netherlands -> R.drawable.ic_flag_nl
                CountryCode.NewCaledonia -> R.drawable.ic_flag_nc
                CountryCode.NewZaeland -> R.drawable.ic_flag_nz
                CountryCode.Nicaragua -> R.drawable.ic_flag_ni
                CountryCode.Niger -> R.drawable.ic_flag_ne
                CountryCode.Nigeria -> R.drawable.ic_flag_ng
                CountryCode.Niue -> R.drawable.ic_flag_nu
                CountryCode.NorthKorea -> R.drawable.ic_flag_kp
                CountryCode.NorthenMarianaIslands -> R.drawable.ic_flag_mp
                CountryCode.Norway -> R.drawable.ic_flag_no
                CountryCode.Oman -> R.drawable.ic_flag_om
                CountryCode.Pakistan -> R.drawable.ic_flag_pk
                CountryCode.Palau -> R.drawable.ic_flag_pw
                CountryCode.Palestine -> R.drawable.ic_flag_ps
                CountryCode.Panama -> R.drawable.ic_flag_pa
                CountryCode.PapuaNewGuinea -> R.drawable.ic_flag_pg
                CountryCode.Paraguay -> R.drawable.ic_flag_py
                CountryCode.Peru -> R.drawable.ic_flag_pe
                CountryCode.Philippines -> R.drawable.ic_flag_ph
                CountryCode.Pitcairn -> R.drawable.ic_flag_pn
                CountryCode.Poland -> R.drawable.ic_flag_pl
                CountryCode.Portugal -> R.drawable.ic_flag_pt
                CountryCode.PuertoRico -> R.drawable.ic_flag_pr
                CountryCode.Qatar -> R.drawable.ic_flag_qa
                CountryCode.RepublicOfCongo -> R.drawable.ic_flag_cg
                CountryCode.Reunion -> R.drawable.ic_flag_re
                CountryCode.Romania -> R.drawable.ic_flag_ro
                CountryCode.Russia -> R.drawable.ic_flag_ru
                CountryCode.Rwanda -> R.drawable.ic_flag_rw
                CountryCode.SaintBarthelemy -> R.drawable.ic_flag_bl
                CountryCode.SaintHelena -> R.drawable.ic_flag_sh
                CountryCode.SaintKittsAndNevis -> R.drawable.ic_flag_kn
                CountryCode.SaintLucia -> R.drawable.ic_flag_lc
                CountryCode.SaintMartin -> R.drawable.ic_flag_mf
                CountryCode.SaintPierreAndMiquelon -> R.drawable.ic_flag_pm
                CountryCode.SaintVincentAndGrenadines -> R.drawable.ic_flag_vc
                CountryCode.Samoa -> R.drawable.ic_flag_ws
                CountryCode.SanMarino -> R.drawable.ic_flag_sm
                CountryCode.SaoTomeAndPrincipe -> R.drawable.ic_flag_st
                CountryCode.SaudiArabia -> R.drawable.ic_flag_sa
                CountryCode.Senegal -> R.drawable.ic_flag_sn
                CountryCode.Serbia -> R.drawable.ic_flag_rs
                CountryCode.Seychelles -> R.drawable.ic_flag_sc
                CountryCode.SierraLeone -> R.drawable.ic_flag_sl
                CountryCode.Singapore -> R.drawable.ic_flag_sg
                CountryCode.SintMarteen -> R.drawable.ic_flag_sx
                CountryCode.Slovakia -> R.drawable.ic_flag_sk
                CountryCode.Slovenia -> R.drawable.ic_flag_si
                CountryCode.SolomonIslands -> R.drawable.ic_flag_sb
                CountryCode.Somalia -> R.drawable.ic_flag_so
                CountryCode.SouthAfrica -> R.drawable.ic_flag_za
                CountryCode.SouthKorea -> R.drawable.ic_flag_kr
                CountryCode.SouthSudan -> R.drawable.ic_flag_ss
                CountryCode.Spain -> R.drawable.ic_flag_es
                CountryCode.SriLanka -> R.drawable.ic_flag_lk
                CountryCode.Sudan -> R.drawable.ic_flag_sd
                CountryCode.Suriname -> R.drawable.ic_flag_sr
                CountryCode.Swaziland -> R.drawable.ic_flag_sz
                CountryCode.Sweden -> R.drawable.ic_flag_se
                CountryCode.Switzerland -> R.drawable.ic_flag_ch
                CountryCode.Syria -> R.drawable.ic_flag_sy
                CountryCode.Taiwan -> R.drawable.ic_flag_tw
                CountryCode.Tajikistan -> R.drawable.ic_flag_tj
                CountryCode.Tanzania -> R.drawable.ic_flag_tz
                CountryCode.Thailand -> R.drawable.ic_flag_th
                CountryCode.Togo -> R.drawable.ic_flag_tg
                CountryCode.Tokelau -> R.drawable.ic_flag_tk
                CountryCode.Tonga -> R.drawable.ic_flag_to
                CountryCode.TrinidadAndTobago -> R.drawable.ic_flag_tt
                CountryCode.Tunisia -> R.drawable.ic_flag_tn
                CountryCode.Turkey -> R.drawable.ic_flag_tr
                CountryCode.Turkmenistan -> R.drawable.ic_flag_tm
                CountryCode.TurksAndCaicosIslands -> R.drawable.ic_flag_tc
                CountryCode.Tuvalu -> R.drawable.ic_flag_tv
                CountryCode.USVirginIslands -> R.drawable.ic_flag_vi
                CountryCode.Uganda -> R.drawable.ic_flag_ug
                CountryCode.Ukraine -> R.drawable.ic_flag_ua
                CountryCode.UnitedArabEmirates -> R.drawable.ic_flag_ae
                CountryCode.UnitedKingdom -> R.drawable.ic_flag_gb
                CountryCode.UnitedStates -> R.drawable.ic_flag_us
                CountryCode.Uzbekistan -> R.drawable.ic_flag_uz
                CountryCode.Vanuatu -> R.drawable.ic_flag_vu
                CountryCode.Vatican -> R.drawable.ic_flag_va
                CountryCode.Venezuela -> R.drawable.ic_flag_ve
                CountryCode.Vietnam -> R.drawable.ic_flag_vn
                CountryCode.WallisAndFutuna -> R.drawable.ic_flag_wf
                CountryCode.Yemen -> R.drawable.ic_flag_ye
                CountryCode.Zambia -> R.drawable.ic_flag_za
                CountryCode.Zimbabwe -> R.drawable.ic_flag_zw

                CountryCode.England -> R.drawable.ic_flag_gb_eng
                CountryCode.NorthernIreland -> R.drawable.ic_flag_gb_nir
                CountryCode.Scotland -> R.drawable.ic_flag_gb_sct
                CountryCode.Wales -> R.drawable.ic_flag_gb_wls
                CountryCode.ShetlandIslands -> R.drawable.ic_flag_gb_zet
                CountryCode.California -> R.drawable.ic_flag_us_ca

                else -> UNKNOWN_COUNTRY_CODE
            }
        }
    }
}